-- Skema Database untuk SI DATA PEGAWAI (Hybrid Sync)

CREATE TABLE IF NOT EXISTS pegawai (
  sid VARCHAR(50) PRIMARY KEY,
  nama_pegawai VARCHAR(100),
  npwp VARCHAR(50),
  no_bpjs VARCHAR(50),
  nama_jabatan_orb VARCHAR(150),
  nama_jabatan_prb VARCHAR(150),
  nama_status_aktif VARCHAR(50),
  nama_status_rumpun VARCHAR(50),
  jenis_kontrak VARCHAR(50),
  nip VARCHAR(50),
  jenis_kelamin VARCHAR(20),
  tmt_kerja_ukpd VARCHAR(100),
  tempat_lahir VARCHAR(100),
  tanggal_lahir DATE,
  agama VARCHAR(20),
  jenjang_pendidikan VARCHAR(50),
  jurusan_pendidikan VARCHAR(100),
  no_tlp VARCHAR(50),
  email VARCHAR(100),
  nama_ukpd VARCHAR(100),
  wilayah_ukpd VARCHAR(50),
  golongan_darah VARCHAR(5),
  gelar_depan VARCHAR(50),
  gelar_belakang VARCHAR(50),
  status_pernikahan VARCHAR(30),
  nama_jenis_pegawai VARCHAR(50),
  catatan_revisi_biodata TEXT,
  alamat_ktp TEXT,
  alamat_domisili TEXT,
  created_at DATETIME,
  updated_at DATETIME,
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME,
  INDEX idx_nip (nip),
  INDEX idx_ukpd (nama_ukpd)
);

CREATE TABLE IF NOT EXISTS username (
  sid VARCHAR(50) PRIMARY KEY,
  nama_ukpd VARCHAR(100),
  username VARCHAR(100),
  password VARCHAR(255),
  hak_akses VARCHAR(50),
  wilayah VARCHAR(50),
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME
);

CREATE TABLE IF NOT EXISTS usulan_mutasi (
  sid VARCHAR(50) PRIMARY KEY,
  id VARCHAR(50),
  nip VARCHAR(50),
  nama_pegawai VARCHAR(100),
  gelar_depan VARCHAR(50),
  gelar_belakang VARCHAR(50),
  pangkat_golongan VARCHAR(50),
  jabatan VARCHAR(150),
  abk_j_lama VARCHAR(50),
  bezetting_j_lama VARCHAR(50),
  nonasn_bezetting_lama VARCHAR(50),
  nonasn_abk_lama VARCHAR(50),
  jabatan_baru VARCHAR(150),
  abk_j_baru VARCHAR(50),
  bezetting_j_baru VARCHAR(50),
  nonasn_bezetting_baru VARCHAR(50),
  nonasn_abk_baru VARCHAR(50),
  nama_ukpd VARCHAR(100),
  ukpd_tujuan VARCHAR(100),
  alasan TEXT,
  tanggal_usulan DATE,
  status VARCHAR(50),
  berkas_path TEXT,
  created_by_ukpd VARCHAR(100),
  created_at DATETIME,
  updated_at DATETIME,
  keterangan TEXT,
  mutasi_id VARCHAR(50),
  jenis_mutasi VARCHAR(50),
  verif_checklist TEXT,
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME
);

CREATE TABLE IF NOT EXISTS usulan_pemutusan_jf (
  sid VARCHAR(50) PRIMARY KEY,
  id VARCHAR(50),
  nip VARCHAR(50),
  pangkat_golongan VARCHAR(50),
  nama_pegawai VARCHAR(100),
  jabatan VARCHAR(150),
  jabatan_baru VARCHAR(150),
  angka_kredit VARCHAR(50),
  alasan_pemutusan TEXT,
  nomor_surat VARCHAR(100),
  tanggal_surat DATE,
  hal VARCHAR(200),
  pimpinan VARCHAR(100),
  asal_surat VARCHAR(100),
  nama_ukpd VARCHAR(100),
  tanggal_usulan DATE,
  status VARCHAR(50),
  berkas_path TEXT,
  created_by_ukpd VARCHAR(100),
  created_at DATETIME,
  updated_at DATETIME,
  keterangan TEXT,
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME
);

CREATE TABLE IF NOT EXISTS refresh_runs (
  refresh_id VARCHAR(50) PRIMARY KEY,
  entity VARCHAR(50),
  status VARCHAR(20),
  started_at DATETIME,
  received_row_count INT DEFAULT 0,
  expected_row_count INT DEFAULT 0,
  last_chunk_index INT DEFAULT -1,
  committed_at DATETIME,
  error TEXT
);

CREATE TABLE IF NOT EXISTS sync_log (
  log_id INT AUTO_INCREMENT PRIMARY KEY,
  sid VARCHAR(50),
  nip VARCHAR(50),
  action VARCHAR(50),
  ok TINYINT,
  message TEXT,
  row_hash VARCHAR(64),
  created_at DATETIME
);

CREATE TABLE IF NOT EXISTS qna (
  sid VARCHAR(50) PRIMARY KEY,
  id VARCHAR(50),
  category VARCHAR(100),
  question TEXT,
  answer TEXT,
  status VARCHAR(50),
  created_at DATETIME,
  updated_at DATETIME,
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME
);

CREATE TABLE IF NOT EXISTS bezetting (
  sid VARCHAR(50) PRIMARY KEY,
  no VARCHAR(50),
  bidang VARCHAR(255),
  subbidang VARCHAR(255),
  nama_jabatan_pergub VARCHAR(255),
  nama_jabatan_permenpan VARCHAR(255),
  jabatan_orb VARCHAR(255),
  pangkat_golongan VARCHAR(50),
  rumpun_jabatan VARCHAR(255),
  kode VARCHAR(50),
  abk VARCHAR(50),
  eksisting VARCHAR(50),
  selisih VARCHAR(50),
  nama_pegawai VARCHAR(255),
  nip VARCHAR(30),
  nrk VARCHAR(30),
  status_formasi VARCHAR(100),
  pendidikan VARCHAR(100),
  keterangan TEXT,
  sisa_formasi_2026 VARCHAR(50),
  kebutuhan_asn_2026 VARCHAR(50),
  perencanaan_kebutuhan VARCHAR(255),
  program_studi VARCHAR(255),
  perencanaan_pendidikan_lanjutan VARCHAR(255),
  ukpd VARCHAR(255),
  wilayah VARCHAR(100),
  sync_status VARCHAR(20),
  sync_error TEXT,
  synced_at DATETIME,
  row_hash VARCHAR(64),
  db_synced_at DATETIME
);